name: fhir_at_rest
description: package to allow restful calls using fhir
version: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.1
  freezed_annotation: ^0.12.0
  dartz: ^0.9.1
  http: ^0.12.2
  fhir: ^0.0.7

dev_dependencies:
  json_serializable: ^3.4.1
  freezed: ^0.12.1
  build_runner: ^1.10.1
  lint: ^1.2.0