name: fhir_at_rest
description: This package builds on the basic FHIR package. It allows easy
  creation of RESTful calls to a FHIR server or FHIR API.
version: 0.0.5
homepage: https://www.fhirfli.dev/
repository: https://github.com/Dokotela/fhir_at_rest

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  dartz: ^0.9.2
  fhir: ^0.0.11
  freezed_annotation: ^0.12.0
  http: ^0.12.2
  json_annotation: ^3.0.1

dev_dependencies:
  build_runner: ^1.10.1
  freezed: ^0.12.2
  json_serializable: ^3.4.1
  test: ^1.15.4
