name: fhir_at_rest
description: This package builds on the basic FHIR package. It allows easy creation of RESTful calls to a FHIR server or FHIR API.
version: 0.0.4
homepage: https://www.fhirfli.dev/
repository: https://github.com/Dokotela/fhir_at_rest

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.1
  freezed_annotation: ^0.12.0
  dartz: ^0.9.1
  http: ^0.12.2
  fhir: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.4.1
  freezed: ^0.12.1
  build_runner: ^1.10.1
