enum Dstu2Types {
  account,
  allergyintolerance,
  condition,
  procedure,
  clinicalimpression,
  familymemberhistory,
  riskassessment,
  detectedissue,
  careplan,
  goal,
  referralrequest,
  procedurerequest,
  nutritionorder,
  visionprescription,
  medication,
  medicationorder,
  medicationadministration,
  medicationdispense,
  medicationstatement,
  immunization,
  immunizationrecommendation,
  observation,
  diagnosticreport,
  diagnosticorder,
  specimen,
  bodysite,
  imagingstudy,
  imagingobjectselection,
  patient,
  practitioner,
  relatedperson,
  organization,
  healthcareservice,
  group,
  location,
  substance,
  person,
  contract,
  device,
  devicecomponent,
  devicemetric,
  encounter,
  episodeofcare,
  communication,
  flag,
  appointment,
  appointmentresponse,
  schedule,
  slot,
  order,
  orderresponse,
  communicationrequest,
  deviceuserequest,
  deviceusestatement,
  processrequest,
  processresponse,
  supplyrequest,
  supplydelivery,
  questionnaire,
  questionnaireresponse,
  provenance,
  auditevent,
  composition,
  documentmanifest,
  documentreference,
  list,
  media,
  binary,
  bundle,
  basic,
  messageheader,
  operationoutcome,
  parameters,
  subscription,
  valueset,
  conceptmap,
  namingsystem,
  structuredefinition,
  dataelement,
  conformance,
  operationdefinition,
  searchparameter,
  implementationguide,
  testscript,
  coverage,
  eligibilityrequest,
  eligibilityresponse,
  enrollmentrequest,
  enrollmentresponse,
  claim,
  claimresponse,
  paymentnotice,
  paymentreconciliation,
  explanationofbenefit,
  none,
}

const Dstu2TypesEnumMap = {
  Dstu2Types.account: 'account',
  Dstu2Types.allergyintolerance: 'allergyintolerance',
  Dstu2Types.condition: 'condition',
  Dstu2Types.procedure: 'procedure',
  Dstu2Types.clinicalimpression: 'clinicalimpression',
  Dstu2Types.familymemberhistory: 'familymemberhistory',
  Dstu2Types.riskassessment: 'riskassessment',
  Dstu2Types.detectedissue: 'detectedissue',
  Dstu2Types.careplan: 'careplan',
  Dstu2Types.goal: 'goal',
  Dstu2Types.referralrequest: 'referralrequest',
  Dstu2Types.procedurerequest: 'procedurerequest',
  Dstu2Types.nutritionorder: 'nutritionorder',
  Dstu2Types.visionprescription: 'visionprescription',
  Dstu2Types.medication: 'medication',
  Dstu2Types.medicationorder: 'medicationorder',
  Dstu2Types.medicationadministration: 'medicationadministration',
  Dstu2Types.medicationdispense: 'medicationdispense',
  Dstu2Types.medicationstatement: 'medicationstatement',
  Dstu2Types.immunization: 'immunization',
  Dstu2Types.immunizationrecommendation: 'immunizationrecommendation',
  Dstu2Types.observation: 'observation',
  Dstu2Types.diagnosticreport: 'diagnosticreport',
  Dstu2Types.diagnosticorder: 'diagnosticorder',
  Dstu2Types.specimen: 'specimen',
  Dstu2Types.bodysite: 'bodysite',
  Dstu2Types.imagingstudy: 'imagingstudy',
  Dstu2Types.imagingobjectselection: 'imagingobjectselection',
  Dstu2Types.patient: 'patient',
  Dstu2Types.practitioner: 'practitioner',
  Dstu2Types.relatedperson: 'relatedperson',
  Dstu2Types.organization: 'organization',
  Dstu2Types.healthcareservice: 'healthcareservice',
  Dstu2Types.group: 'group',
  Dstu2Types.location: 'location',
  Dstu2Types.substance: 'substance',
  Dstu2Types.person: 'person',
  Dstu2Types.contract: 'contract',
  Dstu2Types.device: 'device',
  Dstu2Types.devicecomponent: 'devicecomponent',
  Dstu2Types.devicemetric: 'devicemetric',
  Dstu2Types.encounter: 'encounter',
  Dstu2Types.episodeofcare: 'episodeofcare',
  Dstu2Types.communication: 'communication',
  Dstu2Types.flag: 'flag',
  Dstu2Types.appointment: 'appointment',
  Dstu2Types.appointmentresponse: 'appointmentresponse',
  Dstu2Types.schedule: 'schedule',
  Dstu2Types.slot: 'slot',
  Dstu2Types.order: 'order',
  Dstu2Types.orderresponse: 'orderresponse',
  Dstu2Types.communicationrequest: 'communicationrequest',
  Dstu2Types.deviceuserequest: 'deviceuserequest',
  Dstu2Types.deviceusestatement: 'deviceusestatement',
  Dstu2Types.processrequest: 'processrequest',
  Dstu2Types.processresponse: 'processresponse',
  Dstu2Types.supplyrequest: 'supplyrequest',
  Dstu2Types.supplydelivery: 'supplydelivery',
  Dstu2Types.questionnaire: 'questionnaire',
  Dstu2Types.questionnaireresponse: 'questionnaireresponse',
  Dstu2Types.provenance: 'provenance',
  Dstu2Types.auditevent: 'auditevent',
  Dstu2Types.composition: 'composition',
  Dstu2Types.documentmanifest: 'documentmanifest',
  Dstu2Types.documentreference: 'documentreference',
  Dstu2Types.list: 'list',
  Dstu2Types.media: 'media',
  Dstu2Types.binary: 'binary',
  Dstu2Types.bundle: 'bundle',
  Dstu2Types.basic: 'basic',
  Dstu2Types.messageheader: 'messageheader',
  Dstu2Types.operationoutcome: 'operationoutcome',
  Dstu2Types.parameters: 'parameters',
  Dstu2Types.subscription: 'subscription',
  Dstu2Types.valueset: 'valueset',
  Dstu2Types.conceptmap: 'conceptmap',
  Dstu2Types.namingsystem: 'namingsystem',
  Dstu2Types.structuredefinition: 'structuredefinition',
  Dstu2Types.dataelement: 'dataelement',
  Dstu2Types.conformance: 'conformance',
  Dstu2Types.operationdefinition: 'operationdefinition',
  Dstu2Types.searchparameter: 'searchparameter',
  Dstu2Types.implementationguide: 'implementationguide',
  Dstu2Types.testscript: 'testscript',
  Dstu2Types.coverage: 'coverage',
  Dstu2Types.eligibilityrequest: 'eligibilityrequest',
  Dstu2Types.eligibilityresponse: 'eligibilityresponse',
  Dstu2Types.enrollmentrequest: 'enrollmentrequest',
  Dstu2Types.enrollmentresponse: 'enrollmentresponse',
  Dstu2Types.claim: 'claim',
  Dstu2Types.claimresponse: 'claimresponse',
  Dstu2Types.paymentnotice: 'paymentnotice',
  Dstu2Types.paymentreconciliation: 'paymentreconciliation',
  Dstu2Types.explanationofbenefit: 'explanationofbenefit',
  Dstu2Types.none: 'none',
};
