enum R4Types {
  account,
  activitydefinition,
  adverseevent,
  allergyintolerance,
  appointment,
  appointmentresponse,
  auditevent,
  basic,
  binary,
  biologicallyderivedproduct,
  bodystructure,
  bundle,
  capabilitystatement,
  careplan,
  careteam,
  catalogentry,
  chargeitem,
  chargeitemdefinition,
  claim,
  claimresponse,
  clinicalimpression,
  codesystem,
  communication,
  communicationrequest,
  compartmentdefinition,
  composition,
  conceptmap,
  condition,
  consent,
  contract,
  coverage,
  coverageeligibilityrequest,
  coverageeligibilityresponse,
  detectedissue,
  device,
  devicedefinition,
  devicemetric,
  devicerequest,
  deviceusestatement,
  diagnosticreport,
  documentmanifest,
  documentreference,
  effectevidencesynthesis,
  encounter,
  endpoint,
  enrollmentrequest,
  enrollmentresponse,
  episodeofcare,
  eventdefinition,
  evidence,
  evidencevariable,
  examplescenario,
  explanationofbenefit,
  familymemberhistory,
  flag,
  goal,
  graphdefinition,
  group,
  guidanceresponse,
  healthcareservice,
  imagingstudy,
  immunization,
  immunizationevaluation,
  immunizationrecommendation,
  implementationguide,
  insuranceplan,
  invoice,
  library,
  linkage,
  list_,
  location,
  measure,
  measurereport,
  media,
  medication,
  medicationadministration,
  medicationdispense,
  medicationknowledge,
  medicationrequest,
  medicationstatement,
  medicinalproduct,
  medicinalproductauthorization,
  medicinalproductcontraindication,
  medicinalproductindication,
  medicinalproductingredient,
  medicinalproductinteraction,
  medicinalproductmanufactured,
  medicinalproductpackaged,
  medicinalproductpharmaceutical,
  medicinalproductundesirableeffect,
  messagedefinition,
  messageheader,
  molecularsequence,
  namingsystem,
  nutritionorder,
  observation,
  observationdefinition,
  operationdefinition,
  operationoutcome,
  organization,
  organizationaffiliation,
  parameters,
  patient,
  paymentnotice,
  paymentreconciliation,
  person,
  plandefinition,
  practitioner,
  practitionerrole,
  procedure,
  provenance,
  questionnaire,
  questionnaireresponse,
  relatedperson,
  requestgroup,
  researchdefinition,
  researchelementdefinition,
  researchstudy,
  researchsubject,
  riskassessment,
  riskevidencesynthesis,
  schedule,
  searchparameter,
  servicerequest,
  slot,
  specimen,
  specimendefinition,
  structuredefinition,
  structuremap,
  subscription,
  substance,
  substancenucleicacid,
  substancepolymer,
  substanceprotein,
  substancereferenceinformation,
  substancesourcematerial,
  substancespecification,
  supplydelivery,
  supplyrequest,
  task,
  terminologycapabilities,
  testreport,
  testscript,
  valueset,
  verificationresult,
  visionprescription,
  none,
}

const R4TypesEnumMap = {
  R4Types.account: 'account',
  R4Types.activitydefinition: 'activitydefinition',
  R4Types.adverseevent: 'adverseevent',
  R4Types.allergyintolerance: 'allergyintolerance',
  R4Types.appointment: 'appointment',
  R4Types.appointmentresponse: 'appointmentresponse',
  R4Types.auditevent: 'auditevent',
  R4Types.basic: 'basic',
  R4Types.binary: 'binary',
  R4Types.biologicallyderivedproduct: 'biologicallyderivedproduct',
  R4Types.bodystructure: 'bodystructure',
  R4Types.bundle: 'bundle',
  R4Types.capabilitystatement: 'capabilitystatement',
  R4Types.careplan: 'careplan',
  R4Types.careteam: 'careteam',
  R4Types.catalogentry: 'catalogentry',
  R4Types.chargeitem: 'chargeitem',
  R4Types.chargeitemdefinition: 'chargeitemdefinition',
  R4Types.claim: 'claim',
  R4Types.claimresponse: 'claimresponse',
  R4Types.clinicalimpression: 'clinicalimpression',
  R4Types.codesystem: 'codesystem',
  R4Types.communication: 'communication',
  R4Types.communicationrequest: 'communicationrequest',
  R4Types.compartmentdefinition: 'compartmentdefinition',
  R4Types.composition: 'composition',
  R4Types.conceptmap: 'conceptmap',
  R4Types.condition: 'condition',
  R4Types.consent: 'consent',
  R4Types.contract: 'contract',
  R4Types.coverage: 'coverage',
  R4Types.coverageeligibilityrequest: 'coverageeligibilityrequest',
  R4Types.coverageeligibilityresponse: 'coverageeligibilityresponse',
  R4Types.detectedissue: 'detectedissue',
  R4Types.device: 'device',
  R4Types.devicedefinition: 'devicedefinition',
  R4Types.devicemetric: 'devicemetric',
  R4Types.devicerequest: 'devicerequest',
  R4Types.deviceusestatement: 'deviceusestatement',
  R4Types.diagnosticreport: 'diagnosticreport',
  R4Types.documentmanifest: 'documentmanifest',
  R4Types.documentreference: 'documentreference',
  R4Types.effectevidencesynthesis: 'effectevidencesynthesis',
  R4Types.encounter: 'encounter',
  R4Types.endpoint: 'endpoint',
  R4Types.enrollmentrequest: 'enrollmentrequest',
  R4Types.enrollmentresponse: 'enrollmentresponse',
  R4Types.episodeofcare: 'episodeofcare',
  R4Types.eventdefinition: 'eventdefinition',
  R4Types.evidence: 'evidence',
  R4Types.evidencevariable: 'evidencevariable',
  R4Types.examplescenario: 'examplescenario',
  R4Types.explanationofbenefit: 'explanationofbenefit',
  R4Types.familymemberhistory: 'familymemberhistory',
  R4Types.flag: 'flag',
  R4Types.goal: 'goal',
  R4Types.graphdefinition: 'graphdefinition',
  R4Types.group: 'group',
  R4Types.guidanceresponse: 'guidanceresponse',
  R4Types.healthcareservice: 'healthcareservice',
  R4Types.imagingstudy: 'imagingstudy',
  R4Types.immunization: 'immunization',
  R4Types.immunizationevaluation: 'immunizationevaluation',
  R4Types.immunizationrecommendation: 'immunizationrecommendation',
  R4Types.implementationguide: 'implementationguide',
  R4Types.insuranceplan: 'insuranceplan',
  R4Types.invoice: 'invoice',
  R4Types.library: 'library',
  R4Types.linkage: 'linkage',
  R4Types.list_: 'list_',
  R4Types.location: 'location',
  R4Types.measure: 'measure',
  R4Types.measurereport: 'measurereport',
  R4Types.media: 'media',
  R4Types.medication: 'medication',
  R4Types.medicationadministration: 'medicationadministration',
  R4Types.medicationdispense: 'medicationdispense',
  R4Types.medicationknowledge: 'medicationknowledge',
  R4Types.medicationrequest: 'medicationrequest',
  R4Types.medicationstatement: 'medicationstatement',
  R4Types.medicinalproduct: 'medicinalproduct',
  R4Types.medicinalproductauthorization: 'medicinalproductauthorization',
  R4Types.medicinalproductcontraindication: 'medicinalproductcontraindication',
  R4Types.medicinalproductindication: 'medicinalproductindication',
  R4Types.medicinalproductingredient: 'medicinalproductingredient',
  R4Types.medicinalproductinteraction: 'medicinalproductinteraction',
  R4Types.medicinalproductmanufactured: 'medicinalproductmanufactured',
  R4Types.medicinalproductpackaged: 'medicinalproductpackaged',
  R4Types.medicinalproductpharmaceutical: 'medicinalproductpharmaceutical',
  R4Types.medicinalproductundesirableeffect:
      'medicinalproductundesirableeffect',
  R4Types.messagedefinition: 'messagedefinition',
  R4Types.messageheader: 'messageheader',
  R4Types.molecularsequence: 'molecularsequence',
  R4Types.namingsystem: 'namingsystem',
  R4Types.nutritionorder: 'nutritionorder',
  R4Types.observation: 'observation',
  R4Types.observationdefinition: 'observationdefinition',
  R4Types.operationdefinition: 'operationdefinition',
  R4Types.operationoutcome: 'operationoutcome',
  R4Types.organization: 'organization',
  R4Types.organizationaffiliation: 'organizationaffiliation',
  R4Types.parameters: 'parameters',
  R4Types.patient: 'patient',
  R4Types.paymentnotice: 'paymentnotice',
  R4Types.paymentreconciliation: 'paymentreconciliation',
  R4Types.person: 'person',
  R4Types.plandefinition: 'plandefinition',
  R4Types.practitioner: 'practitioner',
  R4Types.practitionerrole: 'practitionerrole',
  R4Types.procedure: 'procedure',
  R4Types.provenance: 'provenance',
  R4Types.questionnaire: 'questionnaire',
  R4Types.questionnaireresponse: 'questionnaireresponse',
  R4Types.relatedperson: 'relatedperson',
  R4Types.requestgroup: 'requestgroup',
  R4Types.researchdefinition: 'researchdefinition',
  R4Types.researchelementdefinition: 'researchelementdefinition',
  R4Types.researchstudy: 'researchstudy',
  R4Types.researchsubject: 'researchsubject',
  R4Types.riskassessment: 'riskassessment',
  R4Types.riskevidencesynthesis: 'riskevidencesynthesis',
  R4Types.schedule: 'schedule',
  R4Types.searchparameter: 'searchparameter',
  R4Types.servicerequest: 'servicerequest',
  R4Types.slot: 'slot',
  R4Types.specimen: 'specimen',
  R4Types.specimendefinition: 'specimendefinition',
  R4Types.structuredefinition: 'structuredefinition',
  R4Types.structuremap: 'structuremap',
  R4Types.subscription: 'subscription',
  R4Types.substance: 'substance',
  R4Types.substancenucleicacid: 'substancenucleicacid',
  R4Types.substancepolymer: 'substancepolymer',
  R4Types.substanceprotein: 'substanceprotein',
  R4Types.substancereferenceinformation: 'substancereferenceinformation',
  R4Types.substancesourcematerial: 'substancesourcematerial',
  R4Types.substancespecification: 'substancespecification',
  R4Types.supplydelivery: 'supplydelivery',
  R4Types.supplyrequest: 'supplyrequest',
  R4Types.task: 'task',
  R4Types.terminologycapabilities: 'terminologycapabilities',
  R4Types.testreport: 'testreport',
  R4Types.testscript: 'testscript',
  R4Types.valueset: 'valueset',
  R4Types.verificationresult: 'verificationresult',
  R4Types.visionprescription: 'visionprescription',
  R4Types.none: 'none',
};
