enum R5Types {
  account,
  activitydefinition,
  adverseevent,
  allergyintolerance,
  appointment,
  appointmentresponse,
  auditevent,
  basic,
  binary,
  biologicallyderivedproduct,
  bodystructure,
  bundle,
  capabilitystatement,
  capabilitystatement2,
  careplan,
  careteam,
  catalogentry,
  chargeitem,
  chargeitemdefinition,
  claim,
  claimresponse,
  clinicalimpression,
  clinicaluseissue,
  codesystem,
  communication,
  communicationrequest,
  compartmentdefinition,
  composition,
  conceptmap,
  condition,
  conditiondefinition,
  consent,
  contract,
  coverage,
  coverageeligibilityrequest,
  coverageeligibilityresponse,
  detectedissue,
  device,
  devicedefinition,
  devicemetric,
  devicerequest,
  deviceusestatement,
  diagnosticreport,
  documentmanifest,
  documentreference,
  encounter,
  endpoint,
  enrollmentrequest,
  enrollmentresponse,
  episodeofcare,
  eventdefinition,
  evidence,
  evidencevariable,
  examplescenario,
  explanationofbenefit,
  familymemberhistory,
  flag,
  goal,
  graphdefinition,
  group,
  guidanceresponse,
  healthcareservice,
  imagingstudy,
  immunization,
  immunizationevaluation,
  immunizationrecommendation,
  implementationguide,
  insuranceplan,
  invoice,
  library,
  linkage,
  list,
  location,
  measure,
  measurereport,
  medication,
  medicationadministration,
  medicationdispense,
  medicationknowledge,
  medicationrequest,
  medicationusage,
  medicinalproductdefinition,
  regulatedauthorization,
  ingredient,
  manufactureditemdefinition,
  packagedproductdefinition,
  administrableproductdefinition,
  messagedefinition,
  messageheader,
  molecularsequence,
  namingsystem,
  nutritionintake,
  nutritionorder,
  observation,
  observationdefinition,
  operationdefinition,
  operationoutcome,
  organization,
  organizationaffiliation,
  parameters,
  patient,
  paymentnotice,
  paymentreconciliation,
  person,
  plandefinition,
  practitioner,
  practitionerrole,
  procedure,
  provenance,
  questionnaire,
  questionnaireresponse,
  relatedperson,
  requestgroup,
  researchstudy,
  researchsubject,
  riskassessment,
  schedule,
  searchparameter,
  servicerequest,
  slot,
  specimen,
  specimendefinition,
  structuredefinition,
  structuremap,
  subscription,
  substance,
  substancedefinition,
  substancenucleicacid,
  substancepolymer,
  substanceprotein,
  substancereferenceinformation,
  substancesourcematerial,
  supplydelivery,
  supplyrequest,
  task,
  terminologycapabilities,
  testreport,
  testscript,
  topic,
  valueset,
  verificationresult,
  visionprescription,
  none,
}

const R5TypesEnumMap = {
  R5Types.account: 'account',
  R5Types.activitydefinition: 'activitydefinition',
  R5Types.adverseevent: 'adverseevent',
  R5Types.allergyintolerance: 'allergyintolerance',
  R5Types.appointment: 'appointment',
  R5Types.appointmentresponse: 'appointmentresponse',
  R5Types.auditevent: 'auditevent',
  R5Types.basic: 'basic',
  R5Types.binary: 'binary',
  R5Types.biologicallyderivedproduct: 'biologicallyderivedproduct',
  R5Types.bodystructure: 'bodystructure',
  R5Types.bundle: 'bundle',
  R5Types.capabilitystatement: 'capabilitystatement',
  R5Types.capabilitystatement2: 'capabilitystatement2',
  R5Types.careplan: 'careplan',
  R5Types.careteam: 'careteam',
  R5Types.catalogentry: 'catalogentry',
  R5Types.chargeitem: 'chargeitem',
  R5Types.chargeitemdefinition: 'chargeitemdefinition',
  R5Types.claim: 'claim',
  R5Types.claimresponse: 'claimresponse',
  R5Types.clinicalimpression: 'clinicalimpression',
  R5Types.clinicaluseissue: 'clinicaluseissue',
  R5Types.codesystem: 'codesystem',
  R5Types.communication: 'communication',
  R5Types.communicationrequest: 'communicationrequest',
  R5Types.compartmentdefinition: 'compartmentdefinition',
  R5Types.composition: 'composition',
  R5Types.conceptmap: 'conceptmap',
  R5Types.condition: 'condition',
  R5Types.conditiondefinition: 'conditiondefinition',
  R5Types.consent: 'consent',
  R5Types.contract: 'contract',
  R5Types.coverage: 'coverage',
  R5Types.coverageeligibilityrequest: 'coverageeligibilityrequest',
  R5Types.coverageeligibilityresponse: 'coverageeligibilityresponse',
  R5Types.detectedissue: 'detectedissue',
  R5Types.device: 'device',
  R5Types.devicedefinition: 'devicedefinition',
  R5Types.devicemetric: 'devicemetric',
  R5Types.devicerequest: 'devicerequest',
  R5Types.deviceusestatement: 'deviceusestatement',
  R5Types.diagnosticreport: 'diagnosticreport',
  R5Types.documentmanifest: 'documentmanifest',
  R5Types.documentreference: 'documentreference',
  R5Types.encounter: 'encounter',
  R5Types.endpoint: 'endpoint',
  R5Types.enrollmentrequest: 'enrollmentrequest',
  R5Types.enrollmentresponse: 'enrollmentresponse',
  R5Types.episodeofcare: 'episodeofcare',
  R5Types.eventdefinition: 'eventdefinition',
  R5Types.evidence: 'evidence',
  R5Types.evidencevariable: 'evidencevariable',
  R5Types.examplescenario: 'examplescenario',
  R5Types.explanationofbenefit: 'explanationofbenefit',
  R5Types.familymemberhistory: 'familymemberhistory',
  R5Types.flag: 'flag',
  R5Types.goal: 'goal',
  R5Types.graphdefinition: 'graphdefinition',
  R5Types.group: 'group',
  R5Types.guidanceresponse: 'guidanceresponse',
  R5Types.healthcareservice: 'healthcareservice',
  R5Types.imagingstudy: 'imagingstudy',
  R5Types.immunization: 'immunization',
  R5Types.immunizationevaluation: 'immunizationevaluation',
  R5Types.immunizationrecommendation: 'immunizationrecommendation',
  R5Types.implementationguide: 'implementationguide',
  R5Types.insuranceplan: 'insuranceplan',
  R5Types.invoice: 'invoice',
  R5Types.library: 'library',
  R5Types.linkage: 'linkage',
  R5Types.list: 'list',
  R5Types.location: 'location',
  R5Types.measure: 'measure',
  R5Types.measurereport: 'measurereport',
  R5Types.medication: 'medication',
  R5Types.medicationadministration: 'medicationadministration',
  R5Types.medicationdispense: 'medicationdispense',
  R5Types.medicationknowledge: 'medicationknowledge',
  R5Types.medicationrequest: 'medicationrequest',
  R5Types.medicationusage: 'medicationusage',
  R5Types.medicinalproductdefinition: 'medicinalproductdefinition',
  R5Types.regulatedauthorization: 'regulatedauthorization',
  R5Types.ingredient: 'ingredient',
  R5Types.manufactureditemdefinition: 'manufactureditemdefinition',
  R5Types.packagedproductdefinition: 'packagedproductdefinition',
  R5Types.administrableproductdefinition: 'administrableproductdefinition',
  R5Types.messagedefinition: 'messagedefinition',
  R5Types.messageheader: 'messageheader',
  R5Types.molecularsequence: 'molecularsequence',
  R5Types.namingsystem: 'namingsystem',
  R5Types.nutritionintake: 'nutritionintake',
  R5Types.nutritionorder: 'nutritionorder',
  R5Types.observation: 'observation',
  R5Types.observationdefinition: 'observationdefinition',
  R5Types.operationdefinition: 'operationdefinition',
  R5Types.operationoutcome: 'operationoutcome',
  R5Types.organization: 'organization',
  R5Types.organizationaffiliation: 'organizationaffiliation',
  R5Types.parameters: 'parameters',
  R5Types.patient: 'patient',
  R5Types.paymentnotice: 'paymentnotice',
  R5Types.paymentreconciliation: 'paymentreconciliation',
  R5Types.person: 'person',
  R5Types.plandefinition: 'plandefinition',
  R5Types.practitioner: 'practitioner',
  R5Types.practitionerrole: 'practitionerrole',
  R5Types.procedure: 'procedure',
  R5Types.provenance: 'provenance',
  R5Types.questionnaire: 'questionnaire',
  R5Types.questionnaireresponse: 'questionnaireresponse',
  R5Types.relatedperson: 'relatedperson',
  R5Types.requestgroup: 'requestgroup',
  R5Types.researchstudy: 'researchstudy',
  R5Types.researchsubject: 'researchsubject',
  R5Types.riskassessment: 'riskassessment',
  R5Types.schedule: 'schedule',
  R5Types.searchparameter: 'searchparameter',
  R5Types.servicerequest: 'servicerequest',
  R5Types.slot: 'slot',
  R5Types.specimen: 'specimen',
  R5Types.specimendefinition: 'specimendefinition',
  R5Types.structuredefinition: 'structuredefinition',
  R5Types.structuremap: 'structuremap',
  R5Types.subscription: 'subscription',
  R5Types.substance: 'substance',
  R5Types.substancedefinition: 'substancedefinition',
  R5Types.substancenucleicacid: 'substancenucleicacid',
  R5Types.substancepolymer: 'substancepolymer',
  R5Types.substanceprotein: 'substanceprotein',
  R5Types.substancereferenceinformation: 'substancereferenceinformation',
  R5Types.substancesourcematerial: 'substancesourcematerial',
  R5Types.supplydelivery: 'supplydelivery',
  R5Types.supplyrequest: 'supplyrequest',
  R5Types.task: 'task',
  R5Types.terminologycapabilities: 'terminologycapabilities',
  R5Types.testreport: 'testreport',
  R5Types.testscript: 'testscript',
  R5Types.topic: 'topic',
  R5Types.valueset: 'valueset',
  R5Types.verificationresult: 'verificationresult',
  R5Types.visionprescription: 'visionprescription',
  R5Types.none: 'none',
};
