enum Stu3Types {
  account,
  activitydefinition,
  adverseevent,
  allergyintolerance,
  appointment,
  appointmentresponse,
  auditevent,
  basic,
  binary,
  bodysite,
  bundle,
  capabilitystatement,
  careplan,
  careteam,
  chargeitem,
  claim,
  claimresponse,
  clinicalimpression,
  codesystem,
  communication,
  communicationrequest,
  compartmentdefinition,
  composition,
  conceptmap,
  condition,
  consent,
  contract,
  coverage,
  dataelement,
  detectedissue,
  device,
  devicecomponent,
  devicemetric,
  devicerequest,
  deviceusestatement,
  diagnosticreport,
  documentmanifest,
  documentreference,
  eligibilityrequest,
  eligibilityresponse,
  encounter,
  endpoint,
  enrollmentrequest,
  enrollmentresponse,
  episodeofcare,
  expansionprofile,
  explanationofbenefit,
  familymemberhistory,
  flag,
  goal,
  graphdefinition,
  group,
  guidanceresponse,
  healthcareservice,
  imagingmanifest,
  imagingstudy,
  immunization,
  immunizationrecommendation,
  implementationguide,
  library,
  linkage,
  list,
  location,
  measure,
  measurereport,
  media,
  medication,
  medicationadministration,
  medicationdispense,
  medicationrequest,
  medicationstatement,
  messagedefinition,
  messageheader,
  namingsystem,
  nutritionorder,
  observation,
  operationdefinition,
  operationoutcome,
  organization,
  parameters,
  patient,
  paymentnotice,
  paymentreconciliation,
  person,
  plandefinition,
  practitioner,
  practitionerrole,
  procedure,
  procedurerequest,
  processrequest,
  processresponse,
  provenance,
  questionnaire,
  questionnaireresponse,
  referralrequest,
  relatedperson,
  requestgroup,
  researchstudy,
  researchsubject,
  riskassessment,
  schedule,
  searchparameter,
  sequence,
  servicedefinition,
  slot,
  specimen,
  structuredefinition,
  structuremap,
  subscription,
  substance,
  supplydelivery,
  supplyrequest,
  task,
  testreport,
  testscript,
  valueset,
  visionprescription,
  none,
}

const Stu3TypesEnumMap = {
  Stu3Types.account: 'account',
  Stu3Types.activitydefinition: 'activitydefinition',
  Stu3Types.adverseevent: 'adverseevent',
  Stu3Types.allergyintolerance: 'allergyintolerance',
  Stu3Types.appointment: 'appointment',
  Stu3Types.appointmentresponse: 'appointmentresponse',
  Stu3Types.auditevent: 'auditevent',
  Stu3Types.basic: 'basic',
  Stu3Types.binary: 'binary',
  Stu3Types.bodysite: 'bodysite',
  Stu3Types.bundle: 'bundle',
  Stu3Types.capabilitystatement: 'capabilitystatement',
  Stu3Types.careplan: 'careplan',
  Stu3Types.careteam: 'careteam',
  Stu3Types.chargeitem: 'chargeitem',
  Stu3Types.claim: 'claim',
  Stu3Types.claimresponse: 'claimresponse',
  Stu3Types.clinicalimpression: 'clinicalimpression',
  Stu3Types.codesystem: 'codesystem',
  Stu3Types.communication: 'communication',
  Stu3Types.communicationrequest: 'communicationrequest',
  Stu3Types.compartmentdefinition: 'compartmentdefinition',
  Stu3Types.composition: 'composition',
  Stu3Types.conceptmap: 'conceptmap',
  Stu3Types.condition: 'condition',
  Stu3Types.consent: 'consent',
  Stu3Types.contract: 'contract',
  Stu3Types.coverage: 'coverage',
  Stu3Types.dataelement: 'dataelement',
  Stu3Types.detectedissue: 'detectedissue',
  Stu3Types.device: 'device',
  Stu3Types.devicecomponent: 'devicecomponent',
  Stu3Types.devicemetric: 'devicemetric',
  Stu3Types.devicerequest: 'devicerequest',
  Stu3Types.deviceusestatement: 'deviceusestatement',
  Stu3Types.diagnosticreport: 'diagnosticreport',
  Stu3Types.documentmanifest: 'documentmanifest',
  Stu3Types.documentreference: 'documentreference',
  Stu3Types.eligibilityrequest: 'eligibilityrequest',
  Stu3Types.eligibilityresponse: 'eligibilityresponse',
  Stu3Types.encounter: 'encounter',
  Stu3Types.endpoint: 'endpoint',
  Stu3Types.enrollmentrequest: 'enrollmentrequest',
  Stu3Types.enrollmentresponse: 'enrollmentresponse',
  Stu3Types.episodeofcare: 'episodeofcare',
  Stu3Types.expansionprofile: 'expansionprofile',
  Stu3Types.explanationofbenefit: 'explanationofbenefit',
  Stu3Types.familymemberhistory: 'familymemberhistory',
  Stu3Types.flag: 'flag',
  Stu3Types.goal: 'goal',
  Stu3Types.graphdefinition: 'graphdefinition',
  Stu3Types.group: 'group',
  Stu3Types.guidanceresponse: 'guidanceresponse',
  Stu3Types.healthcareservice: 'healthcareservice',
  Stu3Types.imagingmanifest: 'imagingmanifest',
  Stu3Types.imagingstudy: 'imagingstudy',
  Stu3Types.immunization: 'immunization',
  Stu3Types.immunizationrecommendation: 'immunizationrecommendation',
  Stu3Types.implementationguide: 'implementationguide',
  Stu3Types.library: 'library',
  Stu3Types.linkage: 'linkage',
  Stu3Types.list: 'list',
  Stu3Types.location: 'location',
  Stu3Types.measure: 'measure',
  Stu3Types.measurereport: 'measurereport',
  Stu3Types.media: 'media',
  Stu3Types.medication: 'medication',
  Stu3Types.medicationadministration: 'medicationadministration',
  Stu3Types.medicationdispense: 'medicationdispense',
  Stu3Types.medicationrequest: 'medicationrequest',
  Stu3Types.medicationstatement: 'medicationstatement',
  Stu3Types.messagedefinition: 'messagedefinition',
  Stu3Types.messageheader: 'messageheader',
  Stu3Types.namingsystem: 'namingsystem',
  Stu3Types.nutritionorder: 'nutritionorder',
  Stu3Types.observation: 'observation',
  Stu3Types.operationdefinition: 'operationdefinition',
  Stu3Types.operationoutcome: 'operationoutcome',
  Stu3Types.organization: 'organization',
  Stu3Types.parameters: 'parameters',
  Stu3Types.patient: 'patient',
  Stu3Types.paymentnotice: 'paymentnotice',
  Stu3Types.paymentreconciliation: 'paymentreconciliation',
  Stu3Types.person: 'person',
  Stu3Types.plandefinition: 'plandefinition',
  Stu3Types.practitioner: 'practitioner',
  Stu3Types.practitionerrole: 'practitionerrole',
  Stu3Types.procedure: 'procedure',
  Stu3Types.procedurerequest: 'procedurerequest',
  Stu3Types.processrequest: 'processrequest',
  Stu3Types.processresponse: 'processresponse',
  Stu3Types.provenance: 'provenance',
  Stu3Types.questionnaire: 'questionnaire',
  Stu3Types.questionnaireresponse: 'questionnaireresponse',
  Stu3Types.referralrequest: 'referralrequest',
  Stu3Types.relatedperson: 'relatedperson',
  Stu3Types.requestgroup: 'requestgroup',
  Stu3Types.researchstudy: 'researchstudy',
  Stu3Types.researchsubject: 'researchsubject',
  Stu3Types.riskassessment: 'riskassessment',
  Stu3Types.schedule: 'schedule',
  Stu3Types.searchparameter: 'searchparameter',
  Stu3Types.sequence: 'sequence',
  Stu3Types.servicedefinition: 'servicedefinition',
  Stu3Types.slot: 'slot',
  Stu3Types.specimen: 'specimen',
  Stu3Types.structuredefinition: 'structuredefinition',
  Stu3Types.structuremap: 'structuremap',
  Stu3Types.subscription: 'subscription',
  Stu3Types.substance: 'substance',
  Stu3Types.supplydelivery: 'supplydelivery',
  Stu3Types.supplyrequest: 'supplyrequest',
  Stu3Types.task: 'task',
  Stu3Types.testreport: 'testreport',
  Stu3Types.testscript: 'testscript',
  Stu3Types.valueset: 'valueset',
  Stu3Types.visionprescription: 'visionprescription',
  Stu3Types.none: 'none',
};
